### ISSUE TITLE
how to obtain a GenericsContext of nested generics?

### ISSUE THREAD

**Issue by mgood7123** [xvik/generics-resolver#27]
im having trouble figuring out how to create a generics context from a nested generic

```
        GenericsContext {
          current class: public abstract interface java.util.List<E>
          generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}
```
 
and i want to obtain a `GenericsContext` with
 
```
        GenericsContext {
          current class: public class java.util.HashMap<K,V>
          generics map: {K=Serializable[][], V=Pair<Serializable[], C__<StringBuilder>>}
```
instead of
```
        GenericsContext {
          current class: public class java.util.HashMap<K,V>
          generics map: {K=class java.lang.Object, V=class java.lang.Object}
 ```

how can i do this?

**Comment by mgood7123** [comment]
i tried this

```java
            java.lang.reflect.TypeVariable<? extends Class<?>>[] typeParameters = context.currentClass().getTypeParameters();
            StringBuilder acc = new StringBuilder();
            for (int i = 0; i < typeParameters.length; i++) {
                String s = new TypeContext(
                        GenericsResolver.resolve(
                                GenericsUtils.resolveClass(
                                        new ArrayResolver(context.generic(i)).clazz,
                                        GenericsUtils.createGenericsMap(new ArrayResolver(context.generic(i)).clazz, context.resolveGenericsOf(new ArrayResolver(context.generic(i)).clazz))
                                )
                        )
                ).toDetailedString(indent+1);
                Class<?> g = context.generic(i);
                Class<?> c = new ArrayResolver(g).clazz;
                List<Class<?>> classes = context.resolveGenericsOf(c);
                LinkedHashMap<String, Type> map = GenericsUtils.createGenericsMap(c, classes);
                acc.append("\n");
                acc.append("GENERICS MAP OF " +  i + " g: " + g).append("\n");
                acc.append("GENERICS MAP OF " +  i + " c: " + c).append("\n");
                acc.append("GENERICS MAP OF " +  i + " classes: " + classes).append("\n");
                acc.append("GENERICS MAP OF " +  i + " map: " + map).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r c: " + context.resolveGenericsOf(c)).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r c: " + context.resolveType(c)).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r c: " + context.resolveTypeGenerics(c)).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r g: " + context.resolveGenericsOf(g)).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r g: " + context.resolveType(g)).append("\n");
                acc.append("GENERICS MAP OF " +  i + " r g: " + context.resolveTypeGenerics(g)).append("\n");
                extracted(acc, i, g, c, context.genericsMap());
                acc.append(s);
            }
            printStream.println(indent(indent) + "genericParameters: " + typeParameters.length + acc);
            indent--;
            printStream.print(indent(indent) + "}");
            printStream.flush();
            return byteArrayOutputStream.toString();
        }

        private void extracted(StringBuilder acc, int i, Class<?> g, Class<?> c, Map<String, Type> map) {
            acc.append("GENERICS MAP OF " + i + " raw c: " + GenericsResolutionUtils.resolveRawGenerics(c)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw c: " + GenericsResolutionUtils.resolveGenerics(c, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw g: " + GenericsResolutionUtils.resolveRawGenerics(g)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw g: " + GenericsResolutionUtils.resolveGenerics(g, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw c: " + GenericsUtils.resolveClass(c, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw c: " + GenericsUtils.extractTypeGenerics(c, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw c: " + Arrays.toString(GenericsUtils.getGenerics(c, map))).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw g: " + GenericsUtils.resolveClass(g, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw g: " + GenericsUtils.extractTypeGenerics(g, map)).append("\n");
            acc.append("GENERICS MAP OF " + i + " raw g: " + Arrays.toString(GenericsUtils.getGenerics(g, map))).append("\n");
        }
```

but i get this
```
GENERICS MAP OF 0 g: class [Ljava.util.HashMap;
GENERICS MAP OF 0 c: class java.util.HashMap
GENERICS MAP OF 0 classes: [class java.lang.Object, class java.lang.Object]
GENERICS MAP OF 0 map: {K=class java.lang.Object, V=class java.lang.Object}
GENERICS MAP OF 0 r c: [class java.lang.Object, class java.lang.Object]
GENERICS MAP OF 0 r c: class java.util.HashMap
GENERICS MAP OF 0 r c: [class java.lang.Object, class java.lang.Object]
GENERICS MAP OF 0 r g: []
GENERICS MAP OF 0 r g: class [Ljava.util.HashMap;
GENERICS MAP OF 0 r g: []
GENERICS MAP OF 0 raw c: {K=class java.lang.Object, V=class java.lang.Object}
GENERICS MAP OF 0 raw c: {K=class java.lang.Object, V=class java.lang.Object}
GENERICS MAP OF 0 raw g: {}
GENERICS MAP OF 0 raw g: {}
GENERICS MAP OF 0 raw c: class java.util.HashMap
GENERICS MAP OF 0 raw c: {K=class java.lang.Object, V=class java.lang.Object}
GENERICS MAP OF 0 raw c: [class java.lang.Object, class java.lang.Object]
GENERICS MAP OF 0 raw g: class [Ljava.util.HashMap;
GENERICS MAP OF 0 raw g: {}
GENERICS MAP OF 0 raw g: []
```

for this
```
    TypeContext {
      type: interface java.util.List
      context: 
        GenericsContext {
          current class: public abstract interface java.util.List<E>
          is inlying: true
          owner class: null
          owner generics map: {}
          visible generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}
          generics: [class [Ljava.util.HashMap;]
          generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}
          generics scope: CLASS
          generics source: interface java.util.List
          generics of: [class java.lang.Object]
          type generics: [class java.lang.Object]
          generics info: 
            GenericsInfo {
              root class: interface java.util.List
              composing types: [interface java.lang.Iterable, interface java.util.Collection, interface java.util.List]
              types map: {interface java.lang.Iterable={T=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}, interface java.util.Collection={E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}, interface java.util.List={E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}}
            }
        }
```

**Comment by xvik** [comment]
> GenericsContext {
          current class: public abstract interface java.util.List<E>
          generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}

"Sub" context for generic variable should be something like this:

```java
Type genericE = context.genericType("E")

// build sub context from type variable (root context used to resolve possible variables in type)
GenericsContext subContext = context.inlyingType(genericE)
```

Basically, inlying is a type resolution knowing "context" variables (from containing class). 
It is also important to select correct context class before (due to [possibly same variables in different classes in hierarchy](https://github.com/xvik/generics-resolver/issues/25#issuecomment-1465821698))

**Comment by mgood7123** [comment]
so something like this?

```java
try {
    GenericsContext resolve = GenericsResolver.resolve(C__.class);
    GenericsContext foo = resolve.fieldType(TypeContext.getFieldRecursive(C__.class, "foo"));
    TypeContext.printDetailed(foo);
    for (Map.Entry<String, Type> stringTypeEntry : foo.genericsMap().entrySet()) {
        Type type = foo.genericType(stringTypeEntry.getKey());
        while(type instanceof GenericArrayType) {
            type = ((GenericArrayType) type).getGenericComponentType();
        }
        GenericsContext genericsContext = foo.inlyingType(type);
        TypeContext.printDetailed(genericsContext);
    }
} catch (NoSuchFieldException e) {
    throw new RuntimeException(e);
}
```

```
TypeContext {
  type: interface java.util.List
  context: 
    GenericsContext {
      current class: public abstract interface java.util.List<E>
      is inlying: true
      owner class: null
      owner generics map: {}
      visible generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}
      generics: [class [Ljava.util.HashMap;]
      generics map: {E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}
      generics scope: CLASS
      generics source: interface java.util.List
      generics of: [class java.lang.Object]
      type generics: [class java.lang.Object]
      generics info: 
        GenericsInfo {
          root class: interface java.util.List
          composing types: [interface java.lang.Iterable, interface java.util.Collection, interface java.util.List]
          types map: {interface java.lang.Iterable={T=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}, interface java.util.Collection={E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}, interface java.util.List={E=HashMap<Serializable[][], Pair<Serializable[], C__<StringBuilder>>>[]}}
        }
    }
}

TypeContext {
  type: class java.util.HashMap
  context: 
    GenericsContext {
      current class: public class java.util.HashMap<K,V>
      is inlying: true
      owner class: null
      owner generics map: {}
      visible generics map: {K=class [[Ljava.io.Serializable;, V=Pair<Serializable[], C__<StringBuilder>>}
      generics: [class [[Ljava.io.Serializable;, class smallville7123.reflectui.utils.Pair]
      generics map: {K=class [[Ljava.io.Serializable;, V=Pair<Serializable[], C__<StringBuilder>>}
      generics scope: CLASS
      generics source: class java.util.HashMap
      generics of: [class java.lang.Object, class java.lang.Object]
      type generics: [class java.lang.Object, class java.lang.Object]
      generics info: 
        GenericsInfo {
          root class: class java.util.HashMap
          composing types: [class java.util.AbstractMap, class java.util.HashMap, interface java.io.Serializable, interface java.lang.Cloneable, interface java.util.Map]
          types map: {class java.util.AbstractMap={K=class [[Ljava.io.Serializable;, V=Pair<Serializable[], C__<StringBuilder>>}, class java.util.HashMap={K=class [[Ljava.io.Serializable;, V=Pair<Serializable[], C__<StringBuilder>>}, interface java.io.Serializable={}, interface java.lang.Cloneable={}, interface java.util.Map={K=class [[Ljava.io.Serializable;, V=Pair<Serializable[], C__<StringBuilder>>}}
        }
    }
}
```

**Comment by xvik** [comment]
>for (int i = 0; i < foo.currentClass().getTypeParameters().length; i++) { 

could be just 

```java
for(Type type: foo.genericTypes())
```

> while(type instanceof GenericArrayType) {

It also could be a pure array class. Here is a few related methods from master:

```java
   /**
     * @param type type to check
     * @return true if type is array or generic array ({@link GenericArrayType}), false otherwise.
     */
   public static boolean isArray(final Type type) {
        return (type instanceof Class && ((Class) type).isArray()) || type instanceof GenericArrayType;
    }

    /**
     * For example, {@code getArrayComponentType(int[]) == int} and
     * {@code getArrayComponentType(List<String>[]) == List<String>}.
     *
     * @param type array type (class or {@link GenericArrayType}
     * @return array component type
     * @throws IllegalArgumentException if provided type is not array
     * @see #isArray(Type)
     */
    public static Type getArrayComponentType(final Type type) {
        if (!isArray(type)) {
            throw new IllegalArgumentException("Provided type is not an array: "
                    + TypeToStringUtils.toStringType(type));
        }
        if (type instanceof GenericArrayType) {
            return ((GenericArrayType) type).getGenericComponentType();
        } else {
            return ((Class) type).getComponentType();
        }
    }
```

and with it:

```java
        Type type = foo.genericType(i);
        while(isArray(type)) {
            type = getArrayComponentType(type);
        }
```

And, just in case, when you want to get rid of context (no need deeper investigations) you could simply do:

```java
Type pureType = context.resolveType(type)
```

This would replace possible variables in type (repackage type without variables).

**Comment by mgood7123** [comment]
alright, now im having a bit of trouble resolving a self-bound generic

```java
class SS1 <T extends SS1<T>> { T r; }
```

```
Exception in thread "main" java.lang.RuntimeException: OVERFLOW
        at smallville7123.Main.Tests$TypeContext.toDetailedString(Tests.java:817)
        at smallville7123.Main.Tests$TypeContext.toDetailedString(Tests.java:808)
        at smallville7123.Main.Tests$TypeContext.toDetailedString(Tests.java:830)
        at smallville7123.Main.Tests$TypeContext.toDetailedString(Tests.java:808)
```

```java
new TypeContext(SS1.class).findField("r").printDetailed();
```
```java
        public TypeContext(Type type) {
            Type t = resolve(type);
            if (t instanceof Class<?>) {
                context = GenericsResolver.resolve((Class<?>)t);
            } else {
                throw new RuntimeException("resulting type is not an instance of class: " + t);
            }
        }

        TypeContext(GenericsContext context, Type type) {
            this.context = context.inlyingType(resolve(type));
        }

        TypeContext(GenericsContext context) {
            this.context = context;
        }

        private Type resolve(Type type) {
            while(type instanceof GenericArrayType) {
                type = ((GenericArrayType) type).getGenericComponentType();
            }
            if (type instanceof Class<?>) {
                Class<?> aClass = (Class<?>) type;

                while (aClass.isArray()) {
                    rank++;
                    aClass = aClass.getComponentType();
                }
                return aClass;
            } else {
                return type;
            }
        }

        public TypeContextField findField(String fieldName) {
            try {
                return new TypeContextField(this, getFieldRecursive(fieldName));
            } catch (NoSuchFieldException e) {
                throw new RuntimeException(e);
            }
        }

// ...

        public static String toDetailedString(GenericsContext context, int indent) {
            if (indent > 20) {
                throw new RuntimeException("OVERFLOW");
            }
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            PrintStream printStream = new PrintStream(byteArrayOutputStream);
            printStream.println();
            printStream.println(indent(indent) + "TypeContext {");
            indent++;
            printStream.println(indent(indent) + "type: " + context.currentClass());


            StringBuilder acc = new StringBuilder();
            java.lang.reflect.TypeVariable<?>[] typeParameters = context.currentClass().getTypeParameters();
            for (int i = 0; i < context.currentClass().getTypeParameters().length; i++) {
                acc.append(new TypeContext(context, context.genericType(i)).toDetailedString(indent+1));
            }
            printStream.println(indent(indent) + "genericParameters: " + typeParameters.length + acc);
            indent--;
            printStream.print(indent(indent) + "}");
            printStream.flush();
            return byteArrayOutputStream.toString();
        }

```
```java
    static class TypeContextField {
        TypeContext parent;
        Field field;

        TypeContextField(TypeContext parent, Field field) {
            this.parent = parent;
            this.field = field;
        }

        TypeContext getReturnType() {
            return new TypeContext(parent.context.fieldType(field));
        }

        public void printDetailed() {
            System.out.println(toDetailedString());
        }

        public String toDetailedString() {
            return toDetailedString(0);
        }

        private String toDetailedString(int indent) {
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            PrintStream printStream = new PrintStream(byteArrayOutputStream);
            printStream.println();
            printStream.println(indent(indent) + "TypeContext {");
            indent++;
            printStream.println(indent(indent) + "field: " + field);
            printStream.println(indent(indent) + "field type: " + getReturnType().toDetailedString(indent + 1));
            indent--;
            printStream.print(indent(indent) + "}");
            printStream.flush();
            return byteArrayOutputStream.toString();
        }
    }
```

**Comment by mgood7123** [comment]
if i just return a string instead i get
```
TypeContext {
  field: smallville7123.Main.SS1 smallville7123.Main.SS1.r
  field type: 
    TypeContext {
      type: class smallville7123.Main.SS1
      genericParameters: 1
        TypeContext {
          type: class smallville7123.Main.SS1
          genericParameters: 1
            TypeContext {
              type: class smallville7123.Main.SS1
// ...
                                      genericParameters: 1
                                        TypeContext {
                                          type: class smallville7123.Main.SS1
                                          genericParameters: 1<<<<OVERFLOW>>>>
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by mgood7123** [comment]
however
```java
class SS2 extends SS1<SS2> {}
```

correctly resolves without overflow

```
TypeContext {
  field: smallville7123.Main.SS1 smallville7123.Main.SS1.r
  field type: 
    TypeContext {
      type: class smallville7123.Main.SS2
      context: 
        GenericsContext {
          current class: class smallville7123.Main.SS2
          is inlying: true
          owner class: null
          owner generics map: {}
          visible generics map: {}
          generics: []
          generics map: {}
          generics scope: CLASS
          generics source: class smallville7123.Main.SS2
          generics of: []
          type generics: []
          generics info: 
            GenericsInfo {
              root class: class smallville7123.Main.SS2
              composing types: [class smallville7123.Main.SS2, class smallville7123.Main.SS1]
              types map: {class smallville7123.Main.SS2={}, class smallville7123.Main.SS1={T=class smallville7123.Main.SS2}}
            }
        }
      genericParameters: 0
    }
}
```

**Comment by mgood7123** [comment]
i think we might be able to detect this by comparing the `context.genericType` with the `context.currentClass()`

**Comment by mgood7123** [comment]
ok, so now we have

```java
        new TypeContext(S1.class).findField("r").printDetailed();
        new TypeContext(S3.class).findField("r").printDetailed();
        new TypeContext(S6.class).findField("r").printDetailed();
        new TypeContext(SS1.class).findField("r").printDetailed();
        new TypeContext(SS2.class).findField("r").printDetailed();
        new TypeContext(S2.class).findMethods("compareTo")[0].printDetailed();
        new TypeContext(GenericFields.class).findField("a").printDetailed();
        new TypeContext(GenericFields.class).findMethods("aMeth")[0].printDetailed();
```
```java
class GenericFields {
    public List<List<String[]>[]>[] a;
    public List<List<String[]>[]>[] aMeth(List<List<String[][]>[][]>[][] b) { return null; };
}

class SS1 <T extends SS1<T>> { T r; }
class SS2 extends SS1<SS2> {}

class S1 <T extends Comparable<T>> { T r; }
class CC <T> implements Comparable<T> {
    @Override
    public int compareTo(@NotNull T o) {
        return 0;
    }
}
class S3 extends S1<S2> {}
class S2 extends CC<S2> {}
class S22 extends CC<S4> {}
class S4 extends CC<S2> {}
class S5 extends S2 {}
class S6 extends S3 {}
```

```
press any key to continue

GENERICS RESOLVER

TypeContextField {
  field: Comparable r
  field type: 
    TypeContext {
      type: interface java.lang.Comparable
      genericParameters: 1
        TypeContext {
          type: class java.lang.Object
          genericParameters: 0
        }
    }
}
GENERICS RESOLVER

TypeContextField {
  field: S2 r
  field type: 
    TypeContext {
      type: class smallville7123.Main.S2
      genericParameters: 0
    }
}
GENERICS RESOLVER

TypeContextField {
  field: S2 r
  field type: 
    TypeContext {
      type: class smallville7123.Main.S2
      genericParameters: 0
    }
}
GENERICS RESOLVER

TypeContextField {
  field: SS1<SS1> r
  field type: 
    TypeContext {
      type: class smallville7123.Main.SS1
      genericParameters: 1
        SELF BOUND TYPE: class smallville7123.Main.SS1

    }
}
GENERICS RESOLVER

TypeContextField {
  field: SS2 r
  field type: 
    TypeContext {
      type: class smallville7123.Main.SS2
      genericParameters: 0
    }
}
GENERICS RESOLVER

TypeContextMethod {
  method: int compareTo(S2)
  method return type: 
    TypeContext {
      type: class java.lang.Integer
      genericParameters: 0
    }
  genericParameters: 1
    TypeContext {
      type: class smallville7123.Main.S2
      genericParameters: 0
    }
}
GENERICS RESOLVER

TypeContextField {
  field: List<List<String[]>[]> a
  field type: 
    TypeContext {
      type: interface java.util.List
      rank: 1
      genericParameters: 1
        TypeContext {
          type: interface java.util.List
          rank: 1
          genericParameters: 1
            TypeContext {
              type: class java.lang.String
              rank: 1
              genericParameters: 0
            }
        }
    }
}
GENERICS RESOLVER

TypeContextMethod {
  method: List<List<String[]>[]>[] aMeth(List<List<String[][]>[][]>[][])
  method return type: 
    TypeContext {
      type: interface java.util.List
      rank: 1
      genericParameters: 1
        TypeContext {
          type: interface java.util.List
          rank: 1
          genericParameters: 1
            TypeContext {
              type: class java.lang.String
              rank: 1
              genericParameters: 0
            }
        }
    }
  genericParameters: 1
    TypeContext {
      type: interface java.util.List
      rank: 2
      genericParameters: 1
        TypeContext {
          type: interface java.util.List
          rank: 2
          genericParameters: 1
            TypeContext {
              type: class java.lang.String
              rank: 2
              genericParameters: 0
            }
        }
    }
}
```

**Comment by mgood7123** [comment]
so yay i think it can now resolve everything correctly \o/
